import '@/src/app/styles/globals.css';

import type { Metadata, Viewport } from 'next';
import { cn, fontSans } from '@/src/shared/lib/styles';

import AppProviders from '../src/app/providers/AppProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className="scroll-smooth antialiased motion-reduce:scroll-auto"
      suppressHydrationWarning
    >
      <body
        className={cn(
          'min-h-dvh bg-white text-neutral-950 dark:bg-black dark:text-neutral-50 font-sans',
          fontSans.variable,
        )}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
